services:
  react:
    image: node:23-alpine
    working_dir: /app
    volumes:
      - ./react:/app
    # ports:
    #   - 8080:8080
    command: sh -c 'npm install && npm run dev'
    depends_on:
      - api

  api:
    image: node:23-alpine
    working_dir: /app
    volumes:
      - ./api:/app
    # ports:
    #   - 3000:3000
    command: sh -c 'npm i && npm run dev'
    # command: sh -c 'npm i && npm run migrate && npm run seed && npm run dev'
    environment:
      # DB_HOST: mysql_db
      # DB_USER: root
      # DB_PASSWORD: slaptazodis
      # DB_NAME: uginfo
      # DB_PORT: 3306
      - DATABASE_URL=mysql://root:slaptazodis@mysql_db:3306/uginfo
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      mysql_db:
        condition: service_healthy
   

  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: slaptazodis
      MYSQL_DATABASE: uginfo
    volumes:
      # - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - bd_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  
  # adminer:
  #   image: adminer:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8000:8080
  #   depends_on:
  #     - mysql_db
  #   environment:
  #     ADMINER_DEFAULT_SERVER: mysql_db

  nginx:  
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react

volumes:
  bd_data:
