services:
  react:
    image: node:23-alpine
    working_dir: /app
    volumes:
      - ./react:/app
    # ports:
    #   - 8080:8080
    command: sh -c 'npm install && npm run dev'
    depends_on:
      - api

  api:
    image: node:23-alpine
    working_dir: /app
    volumes:
      - ./api:/app
    # ports:
    #   - 3000:3000
    command: sh -c 'npm i && npm start'
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: slaptazodis
      DB_NAME: klientai
      DB_PORT: 3306
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: slaptazodis
      MYSQL_DATABASE: klientai
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - bd_data:/var/lib/mysql
  
  # adminer:
  #   image: adminer:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8000:8080
  #   depends_on:
  #     - mysql_db
  #   environment:
  #     ADMINER_DEFAULT_SERVER: mysql_db

  nginx:  
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react


volumes:
  bd_data:
